# Run from the package root with Rscript tools/generate-thesis-engine.R.
# Generates private static functions, preserving the frozen computations.
source_dir <- "tools/frozen/risdr-0.3.2/R"
files <- sort(list.files(source_dir, pattern = "\\.R$", full.names = TRUE))
e <- new.env(parent = baseenv())
for (file in files) sys.source(file, e, keep.source = FALSE)
all_functions <- ls(e, all.names = TRUE)
all_functions <- all_functions[vapply(mget(all_functions, e), is.function, logical(1))]
public <- c(
  fit_risdr = "fit_risdr_sparse", fit_risdr_dual = "fit_risdr_dual",
  fit_risdr_realdata = "fit_risdr_sparse_realdata",
  C1F = "C1F", compute_penalty_weights = "compute_penalty_weights",
  weighted_soft_threshold = "weighted_soft_threshold",
  weighted_sparsify_directions = "weighted_sparsify_directions",
  fit_sparse_grid = "fit_sparse_grid", summarise_sparsity = "summarise_sparsity",
  dual_pca_scores = "dual_pca_scores", slice_response = "slice_response",
  compute_ic_values = "compute_ic_values", compute_ic = "compute_ic",
  print.risdr = "print.risdr_sparse", summary.risdr = "summary.risdr_sparse",
  print.summary.risdr = "print.summary.risdr_sparse",
  print.risdr_dual = "print.risdr_dual", summary.risdr_dual = "summary.risdr_dual",
  print.risdr_realdata = "print.risdr_sparse_realdata"
)
needed <- names(public)
repeat {
  dependencies <- unique(unlist(lapply(mget(needed, e), function(f)
    intersect(all.names(body(f)), all_functions))))
  expanded <- union(needed, dependencies)
  if (setequal(expanded, needed)) break
  needed <- expanded
}
mapping <- setNames(paste0(".thesis_", needed), needed)
mapping[names(public)] <- public
rewrite <- function(x) {
  if (is.symbol(x)) {
    key <- as.character(x)
    if (key %in% names(mapping)) return(as.name(mapping[[key]]))
    return(x)
  }
  if (is.call(x)) {
    # Preserve external namespace references and field names.
    head <- if (is.symbol(x[[1L]])) as.character(x[[1L]]) else ""
    if (head %in% c("::", ":::")) return(x)
    if (head %in% c("$", "@")) { x[[2L]] <- rewrite(x[[2L]]); return(x) }
    for (i in seq_along(x)) if (!is.null(x[[i]]) && !identical(x[[i]], quote(expr = ))) x[[i]] <- rewrite(x[[i]])
  } else if (is.pairlist(x)) {
    for (i in seq_along(x)) if (!is.null(x[[i]]) && !identical(x[[i]], quote(expr = ))) x[[i]] <- rewrite(x[[i]])
  }
  x
}
class_mapping <- c(risdr = "risdr_sparse", "summary.risdr" = "summary.risdr_sparse",
                   risdr_realdata = "risdr_sparse_realdata")
replace_classes <- function(x) {
  if (is.character(x) && length(x) == 1L && x %in% names(class_mapping))
    return(unname(class_mapping[x]))
  if (is.call(x) || is.pairlist(x))
    for (i in seq_along(x)) if (!is.null(x[[i]]) && !identical(x[[i]], quote(expr = ))) x[[i]] <- replace_classes(x[[i]])
  x
}
doc_text <- paste(readLines("tools/thesis-documentation.R"), collapse = "\n")
doc_blocks <- strsplit(doc_text, "\nNULL\n", fixed = TRUE)[[1L]]
docs <- list()
for (block in doc_blocks) {
  block_lines <- strsplit(block, "\n", fixed = TRUE)[[1L]]
  doc_name <- sub("^#' @name ", "", grep("^#' @name ", block_lines, value = TRUE))
  if (doc_name %in% unname(public)) docs[[doc_name]] <- strsplit(trimws(block), "\n", fixed = TRUE)[[1L]]
}
lines <- c("# Generated by tools/generate-thesis-engine.R. Do not edit by hand.",
           "# Source: frozen risdr 0.3.2. Functions are renamed for API isolation.", "")
for (name in sort(needed)) {
  f <- get(name, e)
  fun <- as.call(list(as.name("function"), rewrite(formals(f)), replace_classes(rewrite(body(f)))))
  assignment <- as.call(list(as.name("<-"), as.name(mapping[[name]]), fun))
  lines <- c(lines, docs[[mapping[[name]]]], deparse(assignment, width.cutoff = 88L), "")
}
writeLines(sub("[ \t]+$", "", head(lines, -1L)), "R/thesis_engine.R")
utils::write.csv(data.frame(frozen = names(mapping), packaged = unname(mapping)),
                 "tools/frozen/FUNCTION_MAPPING.csv", row.names = FALSE)
# Retain the permanent thesis tests using renamed function references.
for (file in list.files("tools/frozen/risdr-0.3.2/tests", pattern = "^test-(survival|dual|realdata).*\\.R$", full.names = TRUE)) {
  tests <- parse(file, keep.source = FALSE)
  output <- c("# Generated from the frozen permanent regression tests.", "")
  for (test in tests) output <- c(output, deparse(replace_classes(rewrite(test)), width.cutoff = 88L), "")
  # The original test deliberately exercises this private contribution helper.
  output <- gsub("risdr:::c1f_variable_contributions", "risdr:::.thesis_c1f_variable_contributions", output, fixed = TRUE)
  writeLines(sub("[ \t]+$", "", head(output, -1L)), file.path("tests/testthat", sub("test-", "test-thesis-", basename(file))))
}
cat("Generated", length(needed), "functions from frozen source.\n")
