# Generated by tools/generate-thesis-engine.R. Do not edit by hand.
# Source: frozen risdr 0.3.2. Functions are renamed for API isolation.

.thesis_.risdr_kernel_slice_labels <- function(y, nslices, response_type, delta = NULL, slice_type = c("quantile",
    "equal_width")) {
    response_type <- match.arg(response_type, c("continuous", "categorical", "survival"))
    slice_type <- match.arg(slice_type)
    if (response_type == "continuous") {
        y <- .thesis_check_y_continuous(y, length(y))
        groups <- .thesis_make_slices(y = y, nslices = nslices, type = slice_type)
        return(list(groups = as.integer(groups), nslices = length(unique(groups)), labels = sort(unique(as.integer(groups))),
            response_type = "continuous"))
    }
    if (response_type == "categorical") {
        if (anyNA(y)) {
            stop("`y` contains missing values.", call. = FALSE)
        }
        groups <- as.integer(as.factor(y))
        return(list(groups = groups, nslices = length(unique(groups)), labels = sort(unique(groups)),
            response_type = "categorical"))
    }
    slice_response(y = y, nslices = nslices, response_type = "survival", delta = delta)
}

.thesis_.risdr_mec_slice_covariances <- function(X, groups) {
    levs <- sort(unique(groups))
    covariances <- vector("list", length(levs))
    counts <- integer(length(levs))
    names(covariances) <- as.character(levs)
    names(counts) <- as.character(levs)
    p <- ncol(X)
    for (i in seq_along(levs)) {
        idx <- which(groups == levs[i])
        counts[i] <- length(idx)
        if (length(idx) <= 1L) {
            covariances[[i]] <- matrix(0, nrow = p, ncol = p)
        }
        else {
            covariances[[i]] <- stats::cov(X[idx, , drop = FALSE])
        }
        covariances[[i]] <- (covariances[[i]] + t(covariances[[i]]))/2
    }
    list(covariances = covariances, counts = counts, labels = levs)
}

.thesis_.risdr_reduced_model_components <- function(y, Z, response_type, delta = NULL, n_active = NULL,
    support_penalty = FALSE, tol = 1e-10) {
    response_type <- match.arg(response_type, c("continuous", "categorical", "survival"))
    Z <- as.matrix(Z)
    n <- nrow(Z)
    d <- ncol(Z)
    if (length(y) != n) {
        stop("Length of `y` must equal nrow(`Z`).", call. = FALSE)
    }
    if (response_type == "survival") {
        if (is.null(delta)) {
            stop("For survival response, `delta` must be supplied.", call. = FALSE)
        }
        if (length(delta) != n) {
            stop("`delta` must have length nrow(`Z`).", call. = FALSE)
        }
        delta <- as.integer(delta)
        if (!all(delta %in% c(0L, 1L))) {
            stop("`delta` must contain only 0/1 values.", call. = FALSE)
        }
        dat <- data.frame(time = as.numeric(y), delta = delta, Z)
        fit <- suppressWarnings(survival::coxph(survival::Surv(time, delta) ~ ., data = dat,
            ties = "efron"))
        loglik <- as.numeric(fit$loglik[2L])
        base_df <- d
    }
    else if (response_type == "continuous") {
        dat <- data.frame(y = as.numeric(y), Z)
        fit <- stats::lm(y ~ ., data = dat)
        loglik <- as.numeric(stats::logLik(fit))
        base_df <- d + 1L
    }
    else {
        y_fac <- as.factor(y)
        nclass <- nlevels(y_fac)
        if (nclass < 2L) {
            stop("Categorical response must contain at least two classes.", call. = FALSE)
        }
        if (nclass == 2L) {
            dat <- data.frame(y = as.numeric(y_fac) - 1L, Z)
            fit <- suppressWarnings(stats::glm(y ~ ., data = dat, family = stats::binomial()))
            loglik <- as.numeric(stats::logLik(fit))
            base_df <- d + 1L
        }
        else {
            if (!requireNamespace("nnet", quietly = TRUE)) {
                stop("Package `nnet` is required for multiclass response.", call. = FALSE)
            }
            dat <- data.frame(y = y_fac, Z)
            fit <- suppressWarnings(nnet::multinom(y ~ ., data = dat, trace = FALSE))
            loglik <- as.numeric(stats::logLik(fit))
            base_df <- (d + 1L) * (nclass - 1L)
        }
    }
    if (support_penalty && !is.null(n_active)) {
        n_active <- as.integer(n_active)
        if (length(n_active) != 1L || is.na(n_active) || n_active < 0L) {
            stop("`n_active` must be a non-negative integer scalar.", call. = FALSE)
        }
        k_eff <- base_df + n_active
    }
    else {
        k_eff <- base_df
    }
    k_eff <- max(as.integer(k_eff), 1L)
    if (d == 1L) {
        vz <- stats::var(as.numeric(Z[, 1L]))
        if (!is.finite(vz)) {
            vz <- tol
        }
        cov_theta <- matrix(max(vz, tol), nrow = 1L, ncol = 1L)
    }
    else {
        cov_theta <- stats::cov(Z)
        cov_theta <- as.matrix(cov_theta)
    }
    cov_theta <- (cov_theta + t(cov_theta))/2
    eigvals <- eigen(cov_theta, symmetric = TRUE, only.values = TRUE)$values
    eigvals <- eigvals[eigvals > tol]
    if (length(eigvals) == 0L) {
        c1f_val <- 0
    }
    else {
        c1f_val <- utils::tail(C1F(eigvals, tol = tol)$c1f, 1L)
    }
    list(n = n, d = d, loglik = loglik, k_eff = k_eff, c1f = as.numeric(c1f_val))
}

.thesis_.risdr_safe_normalise <- function(x, tol = 1e-12) {
    nrm <- sqrt(sum(x^2))
    if (!is.finite(nrm) || nrm < tol) {
        return(x)
    }
    x/nrm
}

.thesis_.risdr_slice_covariance <- function(Z, idx, stabilize_slices, stabilization, eps) {
    p <- ncol(Z)
    if (length(idx) <= 1L) {
        S <- matrix(0, nrow = p, ncol = p)
    }
    else {
        S <- stats::cov(Z[idx, , drop = FALSE])
    }
    S <- (S + t(S))/2
    if (stabilize_slices) {
        S <- .thesis_stabilize_cov(S, method = stabilization, eps = eps)
    }
    S
}

.thesis_.risdr_validate_kernel_response <- function(X, y, response_type, delta = NULL) {
    if (length(y) != nrow(X)) {
        stop("Length of `y` must equal the number of rows in `X`.", call. = FALSE)
    }
    if (anyNA(y)) {
        stop("`y` contains missing values.", call. = FALSE)
    }
    if (response_type == "survival") {
        if (is.null(delta)) {
            stop("For survival response, `delta` must be supplied.", call. = FALSE)
        }
        if (length(delta) != nrow(X)) {
            stop("`delta` must have the same length as `y`.", call. = FALSE)
        }
        if (anyNA(delta)) {
            stop("`delta` contains missing values.", call. = FALSE)
        }
        delta_i <- as.integer(delta)
        if (!all(delta_i %in% c(0L, 1L))) {
            stop("`delta` must contain only 0/1 values.", call. = FALSE)
        }
    }
    invisible(TRUE)
}

#' C1F complexity and induced adaptive weights
#'
#' Computes cumulative scale-invariant covariance complexity from leading
#' eigenvalues and converts the complexity profile to relative weights.
#'
#' @param evals Numeric vector of eigenvalues.
#' @param positive_only Logical; retain only positive eigenvalues.
#' @param cumulative Logical; compute cumulative C1F values.
#' @param tol Numerical tolerance.
#' @return A list with C1F values, induced weights, and processed eigenvalues.
#' @export
#' @name C1F
C1F <- function(evals, positive_only = TRUE, cumulative = TRUE, tol = 1e-10) {
    evals <- as.numeric(evals)
    if (positive_only) {
        evals <- evals[evals > tol]
    }
    if (length(evals) == 0L) {
        return(list(c1f = 0, weights = 1, evals = numeric(0)))
    }
    evals <- sort(evals, decreasing = TRUE)
    c1f_scalar <- function(x) {
        lam_bar <- mean(x)
        if (abs(lam_bar) < tol) {
            return(0)
        }
        sum((x - lam_bar)^2)/(4 * lam_bar^2)
    }
    if (cumulative) {
        c1f_vals <- vapply(seq_along(evals), function(k) {
            c1f_scalar(evals[seq_len(k)])
        }, numeric(1))
    }
    else {
        c1f_vals <- c1f_scalar(evals)
    }
    delta <- c1f_vals - min(c1f_vals)
    weights <- exp(-0.5 * delta)
    weights <- weights/sum(weights)
    list(c1f = c1f_vals, weights = weights, evals = evals)
}

.thesis_c1f_variable_contributions <- function(Sigma, tol = 1e-10) {
    Sigma <- as.matrix(Sigma)
    if (!is.numeric(Sigma) || nrow(Sigma) != ncol(Sigma)) {
        stop("`Sigma` must be a numeric square matrix.", call. = FALSE)
    }
    Sigma <- (Sigma + t(Sigma))/2
    eig <- eigen(Sigma, symmetric = TRUE)
    lambda <- as.numeric(eig$values)
    lambda[!is.finite(lambda) | lambda < tol] <- tol
    lambda_bar <- mean(lambda)
    if (!is.finite(lambda_bar) || lambda_bar <= tol) {
        return(rep(0, nrow(Sigma)))
    }
    spectral_deviation <- (lambda - lambda_bar)^2
    contributions <- as.numeric((eig$vectors^2) %*% spectral_deviation)/(4 * lambda_bar^2)
    contributions[!is.finite(contributions) | contributions < 0] <- 0
    names(contributions) <- colnames(Sigma)
    contributions
}

.thesis_check_cov_matrix <- function(Sigma) {
    if (missing(Sigma) || is.null(Sigma)) {
        stop("`Sigma` must be supplied.", call. = FALSE)
    }
    if (!is.matrix(Sigma) && !is.data.frame(Sigma)) {
        stop("`Sigma` must be a matrix or data frame.", call. = FALSE)
    }
    Sigma <- as.matrix(Sigma)
    if (!is.numeric(Sigma)) {
        stop("`Sigma` must be numeric.", call. = FALSE)
    }
    if (nrow(Sigma) != ncol(Sigma)) {
        stop("`Sigma` must be square.", call. = FALSE)
    }
    if (any(!is.finite(Sigma))) {
        stop("`Sigma` contains non-finite values.", call. = FALSE)
    }
    if (max(abs(Sigma - t(Sigma))) > 1e-08) {
        warning("`Sigma` is not exactly symmetric. It has been symmetrised.", call. = FALSE)
        Sigma <- (Sigma + t(Sigma))/2
    }
    Sigma
}

.thesis_check_missing <- function(X, y) {
    if (anyNA(X)) {
        stop("`X` contains missing values. Please impute missing values before using `fit_risdr()`.",
            call. = FALSE)
    }
    if (anyNA(y)) {
        stop("`y` contains missing values. Please impute or remove missing response values before using `fit_risdr()`.",
            call. = FALSE)
    }
    invisible(TRUE)
}

.thesis_check_nslices <- function(nslices, n) {
    if (!is.numeric(nslices) || length(nslices) != 1) {
        stop("`nslices` must be a single positive integer.", call. = FALSE)
    }
    nslices <- as.integer(nslices)
    if (nslices < 2) {
        stop("`nslices` must be at least 2.", call. = FALSE)
    }
    if (nslices > floor(n/5)) {
        warning("`nslices` is large relative to the sample size. ", "Some slices may contain too few observations.",
            call. = FALSE)
    }
    nslices
}

.thesis_check_X <- function(X) {
    if (missing(X) || is.null(X)) {
        stop("`X` must be supplied.", call. = FALSE)
    }
    if (!is.matrix(X) && !is.data.frame(X)) {
        stop("`X` must be a matrix or data frame.", call. = FALSE)
    }
    X <- as.data.frame(X)
    non_numeric <- names(X)[!vapply(X, is.numeric, logical(1))]
    if (length(non_numeric) > 0) {
        stop("`X` must contain only numeric variables. Non-numeric variables found: ", paste(non_numeric,
            collapse = ", "), call. = FALSE)
    }
    X <- as.matrix(X)
    if (nrow(X) < 5) {
        stop("`X` must contain at least 5 observations.", call. = FALSE)
    }
    if (ncol(X) < 2) {
        stop("`X` must contain at least 2 predictor variables.", call. = FALSE)
    }
    if (any(!is.finite(X), na.rm = TRUE)) {
        stop("`X` contains non-finite values. Please remove or impute them before fitting.",
            call. = FALSE)
    }
    X
}

.thesis_check_y_continuous <- function(y, n) {
    if (missing(y) || is.null(y)) {
        stop("`y` must be supplied.", call. = FALSE)
    }
    if (!is.numeric(y)) {
        stop("For Phase 1, `y` must be numeric because only continuous responses are supported.",
            call. = FALSE)
    }
    y <- as.numeric(y)
    if (length(y) != n) {
        stop("`y` must have length equal to the number of rows in `X`. ", "Expected ", n,
            " but got ", length(y), ".", call. = FALSE)
    }
    if (any(!is.finite(y), na.rm = TRUE)) {
        stop("`y` contains non-finite values. Please remove or impute them before fitting.",
            call. = FALSE)
    }
    y
}

.thesis_compute_dr <- function(X, y, Sigma = NULL, nslices = 6, response_type = c("continuous",
    "categorical", "survival"), delta = NULL, slice_type = c("quantile", "equal_width"),
    stabilize_slices = TRUE, stabilization = c("eigenfloor", "ridge", "nearest_pd"), eps = 1e-08) {
    X <- .thesis_check_X(X)
    response_type <- match.arg(response_type)
    stabilization <- match.arg(stabilization)
    .thesis_.risdr_validate_kernel_response(X = X, y = y, response_type = response_type,
        delta = delta)
    if (is.null(Sigma)) {
        Sigma <- stats::cov(X)
    }
    sl <- .thesis_.risdr_kernel_slice_labels(y = y, nslices = nslices, response_type = response_type,
        delta = delta, slice_type = slice_type)
    slices <- sl$groups
    std <- .thesis_standardize_by_cov(X = X, Sigma = Sigma, eps = eps)
    Z <- std$Z
    n <- nrow(Z)
    p <- ncol(Z)
    I_p <- diag(p)
    M <- matrix(0, nrow = p, ncol = p)
    slice_ids <- sort(unique(slices))
    H_eff <- length(slice_ids)
    p_h <- numeric(H_eff)
    mu_h <- vector("list", H_eff)
    Sigma_h <- vector("list", H_eff)
    names(p_h) <- names(mu_h) <- names(Sigma_h) <- as.character(slice_ids)
    for (h in slice_ids) {
        key <- as.character(h)
        idx <- which(slices == h)
        p_h[key] <- length(idx)/n
        mu_h[[key]] <- matrix(colMeans(Z[idx, , drop = FALSE]), ncol = 1)
        Sigma_h[[key]] <- .thesis_.risdr_slice_covariance(Z = Z, idx = idx, stabilize_slices = stabilize_slices,
            stabilization = stabilization, eps = eps)
    }
    for (h in slice_ids) {
        for (k in slice_ids) {
            key_h <- as.character(h)
            key_k <- as.character(k)
            delta_hk <- mu_h[[key_h]] - mu_h[[key_k]]
            A_hk <- Sigma_h[[key_h]] + Sigma_h[[key_k]] + tcrossprod(delta_hk)
            D_hk <- 2 * I_p - A_hk
            M <- M + p_h[key_h] * p_h[key_k] * (D_hk %*% D_hk)
        }
    }
    M <- (M + t(M))/2
    decomp <- .thesis_decompose_kernel(M)
    B <- std$Sigma_inv_sqrt %*% decomp$directions
    X_centered <- sweep(X, 2, std$center, "-")
    scores <- X_centered %*% B
    list(method = "dr", kernel = decomp$kernel, eigenvalues = decomp$eigenvalues, directions = B,
        z_directions = decomp$directions, scores = scores, slices = slices, slice_metadata = sl,
        center = std$center, sdr_center = std$center, Sigma = Sigma, response_type = response_type)
}

#' Compute one reduced-model information criterion
#'
#' @param y Response vector.
#' @param Z Reduced predictors.
#' @param criterion Criterion name.
#' @param response_type Response type.
#' @param delta Optional event indicator.
#' @param n_active Optional active-support size.
#' @param support_penalty Include active-support size in effective df.
#' @param tol Numerical tolerance.
#' @return Scalar criterion value.
#' @export
#' @name compute_ic
compute_ic <- function(y, Z, criterion = c("cicomp", "icomp", "aic", "caic", "bic"), response_type = c("continuous",
    "categorical", "survival"), delta = NULL, n_active = NULL, support_penalty = FALSE, tol = 1e-10) {
    criterion <- match.arg(criterion)
    response_type <- match.arg(response_type)
    values <- compute_ic_values(y = y, Z = Z, response_type = response_type, delta = delta,
        n_active = n_active, support_penalty = support_penalty, tol = tol)
    unname(values[toupper(criterion)])
}

#' Compute all reduced-model information criteria
#'
#' @param y Response vector.
#' @param Z Reduced predictors.
#' @param response_type Response type.
#' @param delta Optional event indicator.
#' @param n_active Optional active-support size.
#' @param support_penalty Include active-support size in effective df.
#' @param tol Numerical tolerance.
#' @return Named numeric vector containing AIC, BIC, CAIC, ICOMP, CICOMP,
#'   log-likelihood, effective df, and C1F.
#' @export
#' @name compute_ic_values
compute_ic_values <- function(y, Z, response_type = c("continuous", "categorical", "survival"),
    delta = NULL, n_active = NULL, support_penalty = FALSE, tol = 1e-10) {
    response_type <- match.arg(response_type)
    comp <- .thesis_.risdr_reduced_model_components(y = y, Z = Z, response_type = response_type,
        delta = delta, n_active = n_active, support_penalty = support_penalty, tol = tol)
    n <- comp$n
    k <- comp$k_eff
    loglik <- comp$loglik
    c1f <- comp$c1f
    c(AIC = -2 * loglik + 2 * k, BIC = -2 * loglik + log(n) * k, CAIC = -2 * loglik + k *
        (log(n) + 1), ICOMP = -2 * loglik + 2 * c1f + 2 * k, CICOMP = -2 * loglik + k * (log(n) +
        1) + 2 * c1f, logLik = loglik, k_eff = k, C1F = c1f)
}

#' Compute adaptive penalty weights from C1F variable contributions
#'
#' For `mode = "c1f"`, the regularised covariance matrix is decomposed into
#' original-coordinate C1F contributions. Variables with larger contribution
#' receive smaller soft-threshold weights, matching the direction of the
#' historical C1F weighting rule while avoiding the invalid mapping of
#' eigenvalue indices directly to predictor indices. `inverse_c1f` reverses
#' that weighting. `uniform` returns equal weights.
#'
#' @param Sigma Regularised covariance matrix.
#' @param mode One of `"c1f"`, `"inverse_c1f"`, or `"uniform"`.
#' @param tol Numerical tolerance.
#' @return Numeric vector of variable-level penalty weights with mean one.
#' @export
#' @name compute_penalty_weights
compute_penalty_weights <- function(Sigma, mode = c("c1f", "inverse_c1f", "uniform"), tol = 1e-10) {
    mode <- match.arg(mode)
    Sigma <- as.matrix(Sigma)
    if (!is.numeric(Sigma) || nrow(Sigma) != ncol(Sigma)) {
        stop("`Sigma` must be a numeric square matrix.", call. = FALSE)
    }
    p <- ncol(Sigma)
    if (mode == "uniform") {
        return(rep(1, p))
    }
    contribution <- .thesis_c1f_variable_contributions(Sigma = Sigma, tol = tol)
    delta <- contribution - min(contribution)
    raw_weights <- exp(-0.5 * delta)
    if (mode == "inverse_c1f") {
        raw_weights <- 1/pmax(raw_weights, tol)
    }
    out <- .thesis_expand_penalty_weights(raw_weights, p = p, normalise = TRUE, tol = tol)
    if (!is.null(colnames(Sigma))) {
        names(out) <- colnames(Sigma)
    }
    out
}

.thesis_compute_phd <- function(X, y, Sigma = NULL, eps = 1e-08) {
    X <- .thesis_check_X(X)
    y <- .thesis_check_y_continuous(y, nrow(X))
    .thesis_check_missing(X, y)
    if (is.null(Sigma)) {
        Sigma <- stats::cov(X)
    }
    std <- .thesis_standardize_by_cov(X = X, Sigma = Sigma, eps = eps)
    Z <- std$Z
    n <- nrow(Z)
    p <- ncol(Z)
    y_centered <- y - mean(y)
    M <- matrix(0, nrow = p, ncol = p)
    for (i in seq_len(n)) {
        zi <- matrix(Z[i, ], ncol = 1)
        M <- M + y_centered[i] * tcrossprod(zi)
    }
    M <- M/n
    M <- (M + t(M))/2
    decomp <- .thesis_decompose_kernel(M, sort_by_abs = TRUE)
    B <- std$Sigma_inv_sqrt %*% decomp$directions
    X_centered <- sweep(X, 2, std$center, "-")
    scores <- X_centered %*% B
    list(method = "phd", kernel = decomp$kernel, eigenvalues = decomp$eigenvalues, directions = B,
        z_directions = decomp$directions, scores = scores, slices = NULL, slice_metadata = NULL,
        center = std$center, sdr_center = std$center, Sigma = Sigma, response_type = "continuous")
}

.thesis_compute_save <- function(X, y, Sigma = NULL, nslices = 6, response_type = c("continuous",
    "categorical", "survival"), delta = NULL, slice_type = c("quantile", "equal_width"),
    stabilize_slices = TRUE, stabilization = c("eigenfloor", "ridge", "nearest_pd"), eps = 1e-08) {
    X <- .thesis_check_X(X)
    response_type <- match.arg(response_type)
    stabilization <- match.arg(stabilization)
    .thesis_.risdr_validate_kernel_response(X = X, y = y, response_type = response_type,
        delta = delta)
    if (is.null(Sigma)) {
        Sigma <- stats::cov(X)
    }
    sl <- .thesis_.risdr_kernel_slice_labels(y = y, nslices = nslices, response_type = response_type,
        delta = delta, slice_type = slice_type)
    slices <- sl$groups
    std <- .thesis_standardize_by_cov(X = X, Sigma = Sigma, eps = eps)
    Z <- std$Z
    n <- nrow(Z)
    p <- ncol(Z)
    I_p <- diag(p)
    M <- matrix(0, nrow = p, ncol = p)
    slice_ids <- sort(unique(slices))
    for (h in slice_ids) {
        idx <- which(slices == h)
        p_h <- length(idx)/n
        Sigma_h <- .thesis_.risdr_slice_covariance(Z = Z, idx = idx, stabilize_slices = stabilize_slices,
            stabilization = stabilization, eps = eps)
        A_h <- I_p - Sigma_h
        M <- M + p_h * (A_h %*% A_h)
    }
    M <- (M + t(M))/2
    decomp <- .thesis_decompose_kernel(M)
    B <- std$Sigma_inv_sqrt %*% decomp$directions
    X_centered <- sweep(X, 2, std$center, "-")
    scores <- X_centered %*% B
    list(method = "save", kernel = decomp$kernel, eigenvalues = decomp$eigenvalues, directions = B,
        z_directions = decomp$directions, scores = scores, slices = slices, slice_metadata = sl,
        center = std$center, sdr_center = std$center, Sigma = Sigma, response_type = response_type)
}

.thesis_compute_sdr <- function(X, y, method = c("dr", "sir", "save", "phd"), Sigma = NULL,
    nslices = 6, response_type = c("continuous", "categorical", "survival"), delta = NULL,
    ...) {
    method <- match.arg(method)
    response_type <- match.arg(response_type)
    if (method == "sir") {
        return(.thesis_compute_sir(X = X, y = y, Sigma = Sigma, nslices = nslices, response_type = response_type,
            delta = delta, ...))
    }
    if (method == "save") {
        return(.thesis_compute_save(X = X, y = y, Sigma = Sigma, nslices = nslices, response_type = response_type,
            delta = delta, ...))
    }
    if (method == "dr") {
        return(.thesis_compute_dr(X = X, y = y, Sigma = Sigma, nslices = nslices, response_type = response_type,
            delta = delta, ...))
    }
    if (response_type != "continuous") {
        stop("`phd` is currently restricted to continuous responses.", call. = FALSE)
    }
    .thesis_compute_phd(X = X, y = y, Sigma = Sigma, ...)
}

.thesis_compute_sir <- function(X, y, Sigma = NULL, nslices = 6, response_type = c("continuous",
    "categorical", "survival"), delta = NULL, slice_type = c("quantile", "equal_width"),
    eps = 1e-08) {
    X <- .thesis_check_X(X)
    response_type <- match.arg(response_type)
    .thesis_.risdr_validate_kernel_response(X = X, y = y, response_type = response_type,
        delta = delta)
    if (is.null(Sigma)) {
        Sigma <- stats::cov(X)
    }
    sl <- .thesis_.risdr_kernel_slice_labels(y = y, nslices = nslices, response_type = response_type,
        delta = delta, slice_type = slice_type)
    slices <- sl$groups
    std <- .thesis_standardize_by_cov(X = X, Sigma = Sigma, eps = eps)
    Z <- std$Z
    n <- nrow(Z)
    p <- ncol(Z)
    M <- matrix(0, nrow = p, ncol = p)
    slice_ids <- sort(unique(slices))
    for (h in slice_ids) {
        idx <- which(slices == h)
        Zh <- Z[idx, , drop = FALSE]
        p_h <- nrow(Zh)/n
        mu_h <- matrix(colMeans(Zh), ncol = 1)
        M <- M + p_h * tcrossprod(mu_h)
    }
    M <- (M + t(M))/2
    decomp <- .thesis_decompose_kernel(M)
    B <- std$Sigma_inv_sqrt %*% decomp$directions
    X_centered <- sweep(X, 2, std$center, "-")
    scores <- X_centered %*% B
    list(method = "sir", kernel = decomp$kernel, eigenvalues = decomp$eigenvalues, directions = B,
        z_directions = decomp$directions, scores = scores, slices = slices, slice_metadata = sl,
        center = std$center, sdr_center = std$center, Sigma = Sigma, response_type = response_type)
}

.thesis_cov_condition_number <- function(Sigma, eps = 1e-12) {
    Sigma <- .thesis_check_cov_matrix(Sigma)
    eig <- eigen(Sigma, symmetric = TRUE, only.values = TRUE)$values
    eig <- pmax(eig, eps)
    max(eig)/min(eig)
}

.thesis_cov_diagnostics <- function(Sigma, tol = 1e-06) {
    Sigma <- .thesis_check_cov_matrix(Sigma)
    eig <- eigen(Sigma, symmetric = TRUE, only.values = TRUE)$values
    list(min_eigenvalue = min(eig), max_eigenvalue = max(eig), condition_number = .thesis_cov_condition_number(Sigma),
        effective_rank = .thesis_cov_effective_rank(Sigma, tol = tol), eigenvalues = eig)
}

.thesis_cov_effective_rank <- function(Sigma, tol = 1e-06) {
    Sigma <- .thesis_check_cov_matrix(Sigma)
    eig <- eigen(Sigma, symmetric = TRUE, only.values = TRUE)$values
    sum(eig > tol)
}

.thesis_cov_lw <- function(X) {
    X <- .thesis_check_X(X)
    Xc <- scale(X, center = TRUE, scale = FALSE)
    n <- nrow(Xc)
    p <- ncol(Xc)
    S <- crossprod(Xc)/n
    target <- mean(diag(S)) * diag(p)
    phi_mat <- matrix(0, nrow = p, ncol = p)
    for (i in seq_len(n)) {
        xi <- matrix(Xc[i, ], ncol = 1)
        Si <- xi %*% t(xi)
        phi_mat <- phi_mat + (Si - S)^2
    }
    phi <- sum(phi_mat)/n^2
    gamma <- sum((S - target)^2)
    if (gamma < .Machine$double.eps) {
        rho <- 1
    }
    else {
        rho <- phi/gamma
    }
    rho <- max(0, min(1, rho))
    Sigma <- (1 - rho) * S + rho * target
    Sigma <- (Sigma + t(Sigma))/2
    attr(Sigma, "rho") <- rho
    attr(Sigma, "alpha") <- rho
    attr(Sigma, "method") <- "lw"
    Sigma
}

.thesis_cov_mec <- function(X, y, nslices = 6, response_type = c("continuous", "categorical",
    "survival"), delta = NULL, tol = 1e-10, ...) {
    X <- .thesis_check_X(X)
    response_type <- match.arg(response_type)
    if (length(y) != nrow(X)) {
        stop("Length of `y` must equal the number of rows in `X`.", call. = FALSE)
    }
    sl <- slice_response(y = y, nslices = nslices, response_type = response_type, delta = delta)
    groups <- sl$groups
    p <- ncol(X)
    n <- nrow(X)
    slice_info <- .thesis_.risdr_mec_slice_covariances(X = X, groups = groups)
    S_list <- slice_info$covariances
    counts <- slice_info$counts
    H <- length(S_list)
    if (H < 1L) {
        stop("No realised slices were available.", call. = FALSE)
    }
    if (n <= H) {
        stop("Too few observations relative to realised slices for pooled MEC covariance.",
            call. = FALSE)
    }
    Sp <- matrix(0, nrow = p, ncol = p)
    for (h in seq_len(H)) {
        Sp <- Sp + ((counts[h] - 1)/(n - H)) * S_list[[h]]
    }
    Sp <- (Sp + t(Sp))/2
    entropy_vals <- rep(-Inf, H)
    for (h in seq_len(H)) {
        eigvals <- eigen(S_list[[h]], symmetric = TRUE, only.values = TRUE)$values
        eigvals <- eigvals[eigvals > tol]
        if (length(eigvals) > 0L) {
            entropy_vals[h] <- p/2 + 0.5 * sum(log(eigvals)) + p/2 * log(2 * pi)
        }
    }
    if (all(!is.finite(entropy_vals))) {
        stop("No slice supplied a positive-eigenvalue entropy calculation.", call. = FALSE)
    }
    h_star <- which.max(entropy_vals)
    S_star <- S_list[[h_star]]
    mix <- S_star + Sp
    mix <- (mix + t(mix))/2
    eig_mix <- eigen(mix, symmetric = TRUE)
    U <- eig_mix$vectors
    z_star <- diag(t(U) %*% S_star %*% U)
    z_pool <- diag(t(U) %*% Sp %*% U)
    z_mean <- mean(z_star)
    z_mec <- pmax(z_mean, z_pool)
    S_mec0 <- U %*% diag(z_mec, nrow = p) %*% t(U)
    S_mec0 <- (S_mec0 + t(S_mec0))/2
    tr_mec <- sum(diag(S_mec0))
    target <- tr_mec * diag(p)/p
    beta <- tr_mec^2/max(tol, sum(S_mec0 * S_mec0))
    alpha_shape <- 2 * (p * (1 + beta) - 2)/max(tol, p - beta)
    m_val <- alpha_shape/2
    rho <- n/(n + m_val)
    Sigma <- rho * S_mec0 + (1 - rho) * target
    Sigma <- (Sigma + t(Sigma))/2
    attr(Sigma, "rho") <- rho
    attr(Sigma, "alpha") <- rho
    attr(Sigma, "beta") <- beta
    attr(Sigma, "alpha_shape") <- alpha_shape
    attr(Sigma, "entropy_slice") <- h_star
    attr(Sigma, "slice_entropy") <- entropy_vals
    attr(Sigma, "slice_counts") <- counts
    attr(Sigma, "realised_slices") <- H
    attr(Sigma, "response_type") <- response_type
    attr(Sigma, "method") <- "mec"
    Sigma
}

.thesis_cov_oas <- function(X, tol = 1e-10) {
    X <- .thesis_check_X(X)
    n <- nrow(X)
    p <- ncol(X)
    S <- ((n - 1)/n) * stats::cov(X)
    S <- (S + t(S))/2
    eigS <- eigen(S, symmetric = TRUE)
    vecs <- eigS$vectors
    vals <- eigS$values
    vals[vals < tol] <- tol
    lambda_star <- pmax(vals, rep(mean(vals), length(vals)))
    STA <- vecs %*% diag(lambda_star, nrow = p) %*% t(vecs)
    STA <- (STA + t(STA))/2
    tr_sta <- sum(diag(STA))
    tr_sta2 <- sum(STA * STA)
    numerator <- (1 - 2/p) * tr_sta2 + tr_sta^2
    denominator <- (p + 1 - 2/p) * (tr_sta2 - tr_sta^2/p + tr_sta^2)
    if (!is.finite(denominator) || abs(denominator) < tol) {
        rho_oas <- 1
    }
    else {
        rho_oas <- numerator/denominator
    }
    rho_oas <- max(0, min(1, rho_oas))
    target <- tr_sta * diag(p)/p
    OAS <- (1 - rho_oas) * STA + rho_oas * target
    OAS <- (OAS + t(OAS))/2
    tr_oas <- sum(diag(OAS))
    tr_oas2 <- sum(OAS * OAS)
    beta <- tr_oas^2/max(tol, tr_oas2)
    alpha_shape <- 2 * (p * (1 + beta) - 2)/max(tol, p - beta)
    m_val <- alpha_shape/2
    rho <- n/(n + m_val)
    Sigma <- rho * OAS + (1 - rho) * target
    Sigma <- (Sigma + t(Sigma))/2
    attr(Sigma, "rho") <- rho
    attr(Sigma, "alpha") <- rho
    attr(Sigma, "rho_oas") <- rho_oas
    attr(Sigma, "beta") <- beta
    attr(Sigma, "alpha_shape") <- alpha_shape
    attr(Sigma, "method") <- "oas"
    Sigma
}

.thesis_decompose_kernel <- function(M, sort_by_abs = FALSE) {
    M <- as.matrix(M)
    M <- (M + t(M))/2
    if (!is.numeric(M) || nrow(M) != ncol(M)) {
        stop("`M` must be a numeric square matrix.", call. = FALSE)
    }
    eig <- eigen(M, symmetric = TRUE)
    if (sort_by_abs) {
        ord <- order(abs(eig$values), decreasing = TRUE)
    }
    else {
        ord <- order(eig$values, decreasing = TRUE)
    }
    list(kernel = M, eigenvalues = eig$values[ord], directions = eig$vectors[, ord, drop = FALSE])
}

#' Dual PCA score construction for p much larger than n
#'
#' Constructs low-rank sample-space scores without forming a p by p covariance
#' matrix. This is useful when the number of predictors is very large.
#'
#' @param X Numeric predictor matrix with observations in rows.
#' @param dual_rank Number of dual components to retain.
#' @param variance_explained Optional cumulative variance threshold.
#' @param center Logical; if TRUE, centre predictors.
#' @param scale_X Logical; if TRUE, scale predictors.
#' @param eps Numerical tolerance.
#'
#' @return A list containing scores, loadings, singular values, centre, scale,
#'   and retained rank.
#' @export
#' @name dual_pca_scores
dual_pca_scores <- function(X, dual_rank = NULL, variance_explained = NULL, center = TRUE,
    scale_X = TRUE, eps = 1e-10) {
    X <- as.matrix(X)
    if (!is.numeric(X)) {
        stop("`X` must be numeric.", call. = FALSE)
    }
    n <- nrow(X)
    p <- ncol(X)
    x_center <- if (center)
        colMeans(X, na.rm = TRUE)
    else rep(0, p)
    Xc <- sweep(X, 2, x_center, "-")
    x_scale <- rep(1, p)
    if (scale_X) {
        x_scale <- apply(Xc, 2, stats::sd, na.rm = TRUE)
        x_scale[!is.finite(x_scale) | x_scale < eps] <- 1
        Xc <- sweep(Xc, 2, x_scale, "/")
    }
    G <- tcrossprod(Xc)/max(1, n - 1)
    G <- (G + t(G))/2
    eig <- eigen(G, symmetric = TRUE)
    values <- pmax(eig$values, 0)
    positive <- which(values > eps)
    if (length(positive) == 0L) {
        stop("No positive dual eigenvalues found.", call. = FALSE)
    }
    values <- values[positive]
    U <- eig$vectors[, positive, drop = FALSE]
    if (!is.null(variance_explained)) {
        if (variance_explained <= 0 || variance_explained > 1) {
            stop("`variance_explained` must be in (0, 1].", call. = FALSE)
        }
        cumvar <- cumsum(values)/sum(values)
        dual_rank <- which(cumvar >= variance_explained)[1]
    }
    if (is.null(dual_rank)) {
        dual_rank <- min(100L, length(values))
    }
    dual_rank <- min(as.integer(dual_rank), length(values), n - 1L)
    values_r <- values[seq_len(dual_rank)]
    U_r <- U[, seq_len(dual_rank), drop = FALSE]
    singular_values <- sqrt(values_r * max(1, n - 1))
    scores <- U_r %*% diag(singular_values, nrow = dual_rank)
    loadings <- t(Xc) %*% U_r %*% diag(1/pmax(singular_values, eps), nrow = dual_rank)
    rownames(loadings) <- colnames(X)
    colnames(loadings) <- paste0("DualComp", seq_len(dual_rank))
    colnames(scores) <- paste0("DualComp", seq_len(dual_rank))
    rownames(scores) <- rownames(X)
    list(scores = scores, loadings = loadings, singular_values = singular_values, eigenvalues = values_r,
        center = x_center, scale = x_scale, dual_rank = dual_rank)
}

.thesis_estimate_cov <- function(X, y = NULL, method = c("mec", "oas", "lw", "sample", "ridge",
    "user"), nslices = 5L, response_type = c("continuous", "categorical", "survival"), delta = NULL,
    cov_fun = NULL, stabilization = c("eigenfloor", "ridge", "nearest_pd"), shrinkage = 1e-04,
    eps = 1e-08, ...) {
    method <- match.arg(method)
    response_type <- match.arg(response_type)
    stabilization <- match.arg(stabilization)
    X <- as.matrix(X)
    if (!is.numeric(X)) {
        stop("`X` must be numeric.", call. = FALSE)
    }
    Sigma <- switch(method, mec = .thesis_cov_mec(X = X, y = y, nslices = nslices, response_type = response_type,
        delta = delta, tol = min(eps, 1e-10)), oas = .thesis_cov_oas(X = X, tol = min(eps,
        1e-10)), lw = .thesis_cov_lw(X = X), sample = {
        out <- stats::cov(X)
        attr(out, "rho") <- 0
        attr(out, "alpha") <- 0
        attr(out, "method") <- "sample"
        out
    }, ridge = {
        S <- stats::cov(X)
        p <- ncol(S)
        out <- S + shrinkage * diag(p)
        attr(out, "rho") <- shrinkage
        attr(out, "alpha") <- shrinkage
        attr(out, "method") <- "ridge"
        out
    }, user = {
        if (is.null(cov_fun) || !is.function(cov_fun)) {
            stop("`cov_fun` must be supplied when method = 'user'.", call. = FALSE)
        }
        out <- cov_fun(X = X, y = y, nslices = nslices, response_type = response_type, delta = delta,
            ...)
        if (!is.matrix(out)) {
            stop("User covariance estimator must return a matrix.", call. = FALSE)
        }
        if (is.null(attr(out, "alpha"))) {
            attr(out, "alpha") <- NA_real_
        }
        if (is.null(attr(out, "rho"))) {
            attr(out, "rho") <- attr(out, "alpha")
        }
        attr(out, "method") <- "user"
        out
    })
    stored_attrs <- attributes(Sigma)
    Sigma <- .thesis_stabilize_cov(Sigma, method = stabilization, lambda = shrinkage, eps = eps)
    for (nm in setdiff(names(stored_attrs), c("dim", "dimnames"))) {
        attr(Sigma, nm) <- stored_attrs[[nm]]
    }
    attr(Sigma, "method") <- method
    attr(Sigma, "response_type") <- response_type
    Sigma
}

.thesis_expand_penalty_weights <- function(w, p, normalise = TRUE, tol = 1e-10) {
    w <- as.numeric(w)
    if (length(w) == 0L) {
        w <- rep(1, p)
    }
    else if (length(w) == 1L) {
        w <- rep(w, p)
    }
    else if (length(w) != p) {
        w <- rep(w, length.out = p)
    }
    w[!is.finite(w) | w < tol] <- tol
    if (normalise) {
        w <- w/mean(w)
    }
    w
}

.thesis_filter_low_variance <- function(X, variance_quantile = 0.25) {
    vars <- apply(X, 2, stats::var, na.rm = TRUE)
    cutoff <- stats::quantile(vars, probs = variance_quantile, na.rm = TRUE)
    keep <- vars > cutoff
    X_filtered <- X[, keep, drop = FALSE]
    attr(X_filtered, "kept_variables") <- colnames(X)[keep]
    return(X_filtered)
}

#' Fit regularised and information-theoretic sufficient dimension reduction
#'
#' Fits an SDR model using a regularised covariance estimator, a selected
#' inverse-regression kernel, adaptive sparse direction estimation, and
#' information-criterion profiling jointly over structural dimension and
#' sparsity tuning parameter.
#'
#' For `d = NULL`, every candidate dimension from 1 through `d_max` is
#' evaluated over the complete `lambda_grid`. The requested selector then
#' chooses the final `(d, lambda)` pair. For explicit `d`, the same audit grid
#' is retained but the final dimension is fixed and only lambda is selected
#' within that dimension.
#'
#' @param X Numeric predictor matrix or data frame.
#' @param y Response vector. For survival data, observed survival time.
#' @param delta Optional 0/1 event indicator for survival data.
#' @param response_type One of `"continuous"`, `"categorical"`, or
#'   `"survival"`.
#' @param sdr_method One of `"dr"`, `"sir"`, `"save"`, or `"phd"`.
#' @param cov_method One of `"mec"`, `"oas"`, `"lw"`, `"sample"`,
#'   `"ridge"`, or `"user"`.
#' @param stabilize Logical. Stage-3 thesis fits require covariance
#'   stabilisation and therefore currently require `TRUE`.
#' @param stabilization Stabilisation method passed to [estimate_cov()].
#' @param nslices Number of response slices, or slices per censoring-status
#'   group for survival data.
#' @param d Optional fixed structural dimension. If `NULL`, selected by
#'   `selector` from candidates 1 through `d_max`.
#' @param d_max Maximum candidate structural dimension.
#' @param selector One of `"cicomp"`, `"icomp"`, `"bic"`, `"caic"`,
#'   or `"aic"`.
#' @param standardize Logical. Standardise predictor columns before fitting.
#' @param complexity Retained for compatibility. The Stage-3 thesis engine
#'   uses the scale-invariant C1F complexity in ICOMP/CICOMP.
#' @param lambda_grid Non-negative sparsity tuning grid.
#' @param adapt_weights Logical. Use covariance-derived adaptive weights.
#' @param weight_mode One of `"c1f"`, `"inverse_c1f"`, or `"uniform"`.
#' @param penalty_weights Optional user-supplied variable-level weights.
#' @param support_penalty Logical. If `TRUE`, active-support size contributes
#'   to the effective parameter count in the information criteria.
#' @param cov_fun Optional user-defined covariance estimator.
#' @param shrinkage Ridge shrinkage parameter used by [estimate_cov()].
#' @param tol Numerical tolerance.
#' @param ... Additional arguments passed only to a user covariance estimator.
#' @return An object of class `risdr` containing the complete `(d, lambda)`
#'   selection grid, profiled dimension table, selected sparse directions,
#'   reduced predictors, covariance diagnostics, and compatibility fields.
#' @export
#' @details This entry point uses the frozen sparse thesis engine. The
#' existing [fit_risdr()] and [fit_risdr_realdata()] interfaces retain their
#' continuous-response behaviour from version 0.3.1. Survival fits use Efron
#' Cox partial likelihood. Apparent fit statistics and loading ranks are
#' exploratory and do not establish external predictive validity.
#' @examples
#' set.seed(2026)
#' X <- matrix(rnorm(80 * 6), 80)
#' colnames(X) <- paste0("G", 1:6)
#' time <- rexp(80, rate = exp(0.5 * X[, 1]))
#' delta <- rep(c(0L, 1L), 40)
#' fit <- fit_risdr_sparse(
#'   X, time, delta = delta, response_type = "survival",
#'   sdr_method = "sir", cov_method = "oas", nslices = 4,
#'   d_max = 2, lambda_grid = c(0, 0.05)
#' )
#' fit$d
#' predict(fit, X[1:2, , drop = FALSE], type = "risk")
#' @name fit_risdr_sparse
fit_risdr_sparse <- function(X, y, delta = NULL, response_type = c("continuous", "categorical",
    "survival"), sdr_method = c("dr", "sir", "save", "phd"), cov_method = c("mec", "oas",
    "lw", "sample", "ridge", "user"), stabilize = TRUE, stabilization = c("eigenfloor", "ridge",
    "nearest_pd"), nslices = 6L, d = NULL, d_max = 10L, selector = c("cicomp", "icomp", "bic",
    "caic", "aic"), standardize = TRUE, complexity = "C1F", lambda_grid = seq(0, 0.3, length.out = 10L),
    adapt_weights = TRUE, weight_mode = c("c1f", "inverse_c1f", "uniform"), penalty_weights = NULL,
    support_penalty = FALSE, cov_fun = NULL, shrinkage = 1e-04, tol = 1e-10, ...) {
    X <- as.matrix(X)
    if (!is.numeric(X)) {
        stop("`X` must be numeric.", call. = FALSE)
    }
    if (nrow(X) < 3L || ncol(X) < 1L) {
        stop("`X` must contain at least three rows and one predictor.", call. = FALSE)
    }
    if (anyNA(X) || any(!is.finite(X))) {
        stop("`X` must contain only finite, non-missing values.", call. = FALSE)
    }
    response_type <- match.arg(response_type)
    sdr_method <- match.arg(sdr_method)
    cov_method <- match.arg(cov_method)
    stabilization <- match.arg(stabilization)
    selector <- match.arg(selector)
    weight_mode <- match.arg(weight_mode)
    if (!isTRUE(stabilize)) {
        stop("Stage-3 unified thesis fitting currently requires `stabilize = TRUE`.", call. = FALSE)
    }
    if (!identical(toupper(as.character(complexity)[1L]), "C1F")) {
        stop("Stage-3 unified thesis fitting currently uses C1F complexity only.", call. = FALSE)
    }
    n <- nrow(X)
    p <- ncol(X)
    if (length(y) != n) {
        stop("Length of `y` must equal nrow(`X`).", call. = FALSE)
    }
    if (anyNA(y)) {
        stop("`y` contains missing values.", call. = FALSE)
    }
    if (response_type %in% c("continuous", "survival")) {
        y <- as.numeric(y)
        if (any(!is.finite(y))) {
            stop("Numeric responses must be finite.", call. = FALSE)
        }
    }
    if (response_type == "survival") {
        if (is.null(delta)) {
            stop("For survival response, `delta` must be supplied.", call. = FALSE)
        }
        if (length(delta) != n || anyNA(delta)) {
            stop("`delta` must be complete and have length nrow(`X`).", call. = FALSE)
        }
        delta <- as.integer(delta)
        if (!all(delta %in% c(0L, 1L))) {
            stop("`delta` must contain only 0/1 values.", call. = FALSE)
        }
        if (any(y <= 0)) {
            stop("Survival times must be strictly positive.", call. = FALSE)
        }
    }
    if (sdr_method == "phd" && response_type != "continuous") {
        stop("`phd` is currently restricted to continuous responses.", call. = FALSE)
    }
    nslices <- as.integer(nslices)
    if (length(nslices) != 1L || is.na(nslices) || nslices < 1L) {
        stop("`nslices` must be a positive integer.", call. = FALSE)
    }
    d_max <- as.integer(d_max)
    if (length(d_max) != 1L || is.na(d_max) || d_max < 1L) {
        stop("`d_max` must be a positive integer.", call. = FALSE)
    }
    d_max <- min(d_max, p, n - 1L)
    requested_d <- d
    if (!is.null(d)) {
        d <- as.integer(d)
        if (length(d) != 1L || is.na(d) || d < 1L || d > d_max) {
            stop("Explicit `d` must lie between 1 and `d_max`.", call. = FALSE)
        }
    }
    lambda_grid <- sort(unique(as.numeric(lambda_grid)))
    if (length(lambda_grid) < 1L || anyNA(lambda_grid) || any(!is.finite(lambda_grid)) ||
        any(lambda_grid < 0)) {
        stop("`lambda_grid` must contain finite non-negative values.", call. = FALSE)
    }
    if (length(support_penalty) != 1L || is.na(support_penalty)) {
        stop("`support_penalty` must be TRUE or FALSE.", call. = FALSE)
    }
    original_colnames <- colnames(X)
    if (is.null(original_colnames)) {
        original_colnames <- paste0("X", seq_len(p))
        colnames(X) <- original_colnames
    }
    if (anyNA(original_colnames) || any(!nzchar(original_colnames)) || anyDuplicated(original_colnames)) {
        stop("Predictor names must be non-missing, non-empty, and unique.", call. = FALSE)
    }
    if (isTRUE(standardize)) {
        center <- colMeans(X)
        scale <- apply(X, 2L, stats::sd)
        bad_scale <- !is.finite(scale) | scale <= tol
        if (any(bad_scale)) {
            scale[bad_scale] <- 1
        }
        X_work <- sweep(X, 2L, center, "-")
        X_work <- sweep(X_work, 2L, scale, "/")
    }
    else {
        center <- rep(0, p)
        scale <- rep(1, p)
        X_work <- X
    }
    colnames(X_work) <- original_colnames
    Sigma <- .thesis_estimate_cov(X = X_work, y = y, method = cov_method, nslices = nslices,
        response_type = response_type, delta = delta, cov_fun = cov_fun, stabilization = stabilization,
        shrinkage = shrinkage, eps = max(tol, 1e-08), ...)
    Sigma_raw <- Sigma
    sdr_fit <- .thesis_compute_sdr(X = X_work, y = y, method = sdr_method, Sigma = Sigma,
        nslices = nslices, response_type = response_type, delta = delta, eps = max(tol, 1e-08))
    dense_directions <- as.matrix(sdr_fit$directions)
    if (nrow(dense_directions) != p) {
        stop("Dense SDR direction matrix has unexpected row dimension.", call. = FALSE)
    }
    d_max <- min(d_max, ncol(dense_directions))
    if (!is.null(d) && d > d_max) {
        stop("Explicit `d` exceeds the available SDR directions.", call. = FALSE)
    }
    rownames(dense_directions) <- original_colnames
    sdr_center <- sdr_fit$sdr_center
    if (is.null(sdr_center)) {
        sdr_center <- colMeans(X_work)
    }
    X_score <- sweep(X_work, 2L, sdr_center, "-")
    if (is.null(penalty_weights)) {
        if (isTRUE(adapt_weights)) {
            penalty_weights_final <- compute_penalty_weights(Sigma = Sigma, mode = weight_mode,
                tol = tol)
        }
        else {
            penalty_weights_final <- rep(1, p)
        }
    }
    else {
        penalty_weights_final <- .thesis_expand_penalty_weights(penalty_weights, p = p, normalise = TRUE,
            tol = tol)
    }
    names(penalty_weights_final) <- original_colnames
    candidate_dims <- seq_len(d_max)
    grid_rows <- vector("list", length(candidate_dims) * length(lambda_grid))
    fit_registry <- vector("list", length(candidate_dims) * length(lambda_grid))
    row_id <- 0L
    for (d_i in candidate_dims) {
        sparse_i <- fit_sparse_grid(directions = dense_directions, d = d_i, lambda_grid = lambda_grid,
            penalty_weights = penalty_weights_final, adapt_weights = FALSE, Sigma = Sigma,
            weight_mode = weight_mode, tol = tol)
        for (lambda_i in seq_along(lambda_grid)) {
            row_id <- row_id + 1L
            V_i <- as.matrix(sparse_i$fits[[lambda_i]])
            rownames(V_i) <- original_colnames
            colnames(V_i) <- paste0("RISDR_Dim", seq_len(d_i))
            Z_i <- X_score %*% V_i
            colnames(Z_i) <- paste0("Z", seq_len(d_i))
            sparsity_i <- summarise_sparsity(V_i, tol = max(tol, 1e-08))
            ic_i <- tryCatch(compute_ic_values(y = y, Z = Z_i, response_type = response_type,
                delta = delta, n_active = sparsity_i$n_active, support_penalty = support_penalty,
                tol = tol), error = function(e) e)
            if (inherits(ic_i, "error")) {
                crit <- c(AIC = Inf, BIC = Inf, CAIC = Inf, ICOMP = Inf, CICOMP = Inf, logLik = NA_real_,
                  k_eff = NA_real_, C1F = NA_real_)
                valid <- FALSE
                error_message <- conditionMessage(ic_i)
            }
            else {
                crit <- ic_i
                valid <- all(is.finite(crit[c("AIC", "BIC", "CAIC", "ICOMP", "CICOMP")]))
                error_message <- NA_character_
            }
            grid_rows[[row_id]] <- data.frame(d = d_i, lambda = lambda_grid[lambda_i], n_active = sparsity_i$n_active,
                active_fraction = sparsity_i$n_active/p, AIC = unname(crit["AIC"]), BIC = unname(crit["BIC"]),
                CAIC = unname(crit["CAIC"]), ICOMP = unname(crit["ICOMP"]), CICOMP = unname(crit["CICOMP"]),
                logLik = unname(crit["logLik"]), k_eff = unname(crit["k_eff"]), C1F = unname(crit["C1F"]),
                valid = valid, error_message = error_message, stringsAsFactors = FALSE)
            fit_registry[[row_id]] <- list(directions = V_i, scores = Z_i, sparsity = sparsity_i)
        }
    }
    selection_grid <- do.call(rbind, grid_rows)
    rownames(selection_grid) <- NULL
    if (!any(selection_grid$valid)) {
        stop("No valid (d, lambda) candidate could be fitted.", call. = FALSE)
    }
    criterion_names <- c("AIC", "BIC", "CAIC", "ICOMP", "CICOMP")
    d_table_rows <- lapply(candidate_dims, function(d_i) {
        rows_d <- which(selection_grid$d == d_i)
        out_d <- data.frame(d = d_i, AIC = Inf, BIC = Inf, CAIC = Inf, ICOMP = Inf, CICOMP = Inf,
            lambda_AIC = NA_real_, lambda_BIC = NA_real_, lambda_CAIC = NA_real_, lambda_ICOMP = NA_real_,
            lambda_CICOMP = NA_real_, stringsAsFactors = FALSE)
        for (criterion_i in criterion_names) {
            values_i <- selection_grid[rows_d, criterion_i]
            finite_i <- which(is.finite(values_i))
            if (length(finite_i) > 0L) {
                local_best <- finite_i[which.min(values_i[finite_i])]
                global_best <- rows_d[local_best]
                out_d[[criterion_i]] <- selection_grid[[criterion_i]][global_best]
                out_d[[paste0("lambda_", criterion_i)]] <- selection_grid$lambda[global_best]
            }
        }
        out_d
    })
    d_table <- do.call(rbind, d_table_rows)
    rownames(d_table) <- NULL
    selector_col <- toupper(selector)
    if (is.null(requested_d)) {
        eligible <- which(is.finite(selection_grid[[selector_col]]))
    }
    else {
        eligible <- which(selection_grid$d == d & is.finite(selection_grid[[selector_col]]))
    }
    if (length(eligible) == 0L) {
        stop("No finite candidate exists for the requested selector.", call. = FALSE)
    }
    best_index <- eligible[which.min(selection_grid[[selector_col]][eligible])]
    selected_d <- selection_grid$d[best_index]
    best_lambda <- selection_grid$lambda[best_index]
    selected_fit <- fit_registry[[best_index]]
    directions <- selected_fit$directions
    reduced_predictors <- selected_fit$scores
    scores <- reduced_predictors
    criterion_dimensions <- stats::setNames(integer(length(criterion_names)), criterion_names)
    criterion_lambdas <- stats::setNames(numeric(length(criterion_names)), criterion_names)
    for (criterion_i in criterion_names) {
        finite_rows <- which(is.finite(selection_grid[[criterion_i]]))
        best_i <- finite_rows[which.min(selection_grid[[criterion_i]][finite_rows])]
        criterion_dimensions[criterion_i] <- selection_grid$d[best_i]
        criterion_lambdas[criterion_i] <- selection_grid$lambda[best_i]
    }
    comparator_scores <- stats::setNames(as.numeric(selection_grid[best_index, criterion_names,
        drop = TRUE]), criterion_names)
    rows_selected_d <- which(selection_grid$d == selected_d)
    criteria_grid <- stats::setNames(selection_grid[[selector_col]][rows_selected_d], paste0("lambda_",
        format(selection_grid$lambda[rows_selected_d], trim = TRUE)))
    loadings <- data.frame(variable = original_colnames, directions, check.names = FALSE,
        stringsAsFactors = FALSE)
    downstream_fit <- NULL
    if (response_type == "survival") {
        downstream_data <- data.frame(time = y, delta = delta, reduced_predictors)
        downstream_fit <- suppressWarnings(survival::coxph(survival::Surv(time, delta) ~
            ., data = downstream_data, ties = "efron"))
    }
    else if (response_type == "continuous") {
        downstream_data <- data.frame(y = y, reduced_predictors)
        downstream_fit <- stats::lm(y ~ ., data = downstream_data)
    }
    else {
        y_fac <- as.factor(y)
        downstream_data <- data.frame(y = y_fac, reduced_predictors)
        if (nlevels(y_fac) == 2L) {
            downstream_fit <- stats::glm(y ~ ., data = downstream_data, family = stats::binomial())
        }
        else {
            if (!requireNamespace("nnet", quietly = TRUE)) {
                stop("Package `nnet` is required for multiclass response.", call. = FALSE)
            }
            downstream_fit <- nnet::multinom(y ~ ., data = downstream_data, trace = FALSE)
        }
    }
    out <- list(call = match.call(), X = X, y = y, delta = delta, X_work = X_work, center = center,
        scale = scale, standardize = standardize, response_type = response_type, sdr_method = sdr_method,
        cov_method = cov_method, stabilize = stabilize, stabilization = stabilization, Sigma_raw = Sigma_raw,
        Sigma = Sigma, covariance = Sigma, kernel = sdr_fit$kernel, eigenvalues = sdr_fit$eigenvalues,
        dense_directions = dense_directions, directions = directions, z_directions = sdr_fit$z_directions,
        scores = scores, reduced_predictors = reduced_predictors, slices = sdr_fit$slices,
        slice_metadata = sdr_fit$slice_metadata, nslices = nslices, requested_d = requested_d,
        d = selected_d, d_max = d_max, d_candidates = candidate_dims, d_table = d_table,
        selector = selector, selection_grid = selection_grid, lambda_grid = lambda_grid,
        best_lambda = best_lambda, criteria_grid = criteria_grid, comparator_scores = comparator_scores,
        criterion_dimensions = criterion_dimensions, criterion_lambdas = criterion_lambdas,
        penalty_weights = penalty_weights_final, adapt_weights = adapt_weights, weight_mode = weight_mode,
        support_penalty = support_penalty, complexity = "C1F", selected_sparsity = selected_fit$sparsity,
        downstream_fit = downstream_fit, sdr_center = sdr_center, loadings = loadings)
    class(out) <- "risdr_sparse"
    out
}

#' Fit dual high-dimensional RISDR
#'
#' Constructs a low-rank PCA score representation, fits the unified RISDR
#' core in that score space, maps the dense and selected sparse SDR directions
#' back to the original predictor coordinates, and ranks variables using the
#' Euclidean loading norm across only the selected sparse directions.
#'
#' The inner RISDR standardisation scale is explicitly undone before mapping
#' directions through the PCA loadings. The returned reduced predictors are
#' taken directly from the fitted core and are therefore exactly aligned with
#' the model used for information-criterion selection.
#'
#' @param X Numeric high-dimensional predictor matrix.
#' @param y Response vector. For survival data, observed time.
#' @param delta Optional 0/1 event indicator.
#' @param response_type One of `"continuous"`, `"categorical"`, or
#'   `"survival"`.
#' @param dual_rank Maximum retained PCA rank.
#' @param variance_explained Optional cumulative variance threshold.
#' @param d Optional fixed structural dimension. If `NULL`, selected by
#'   `selector`.
#' @param d_max Maximum candidate structural dimension.
#' @param nslices Number of slices, or slices per censoring-status group.
#' @param sdr_method SDR method.
#' @param cov_method Covariance method.
#' @param selector Information criterion used to select `(d, lambda)`.
#' @param lambda_grid Sparsity tuning grid.
#' @param adapt_weights Logical. Use adaptive penalty weights.
#' @param weight_mode Adaptive weighting mode.
#' @param support_penalty Logical. Include active support in criterion df.
#' @param standardize_dual Logical. Standardise retained PCA scores inside
#'   [fit_risdr_sparse()].
#' @param gene_select_top Optional number of top-ranked variables.
#' @param gene_select_quantile Quantile used when `gene_select_top` is NULL.
#' @param center Logical. Centre predictors before dual PCA.
#' @param scale_X Logical. Scale predictors before dual PCA.
#' @param verbose Logical. Emit progress messages.
#' @param ... Additional arguments passed to [fit_risdr_sparse()].
#' @return An object of class `risdr_dual`.
#' @export
#' @details This entry point uses the frozen sparse thesis engine. The
#' existing [fit_risdr()] and [fit_risdr_realdata()] interfaces retain their
#' continuous-response behaviour from version 0.3.1. Survival fits use Efron
#' Cox partial likelihood. Apparent fit statistics and loading ranks are
#' exploratory and do not establish external predictive validity.
#' @examples
#' set.seed(2026)
#' X <- matrix(rnorm(80 * 6), 80)
#' colnames(X) <- paste0("G", 1:6)
#' time <- rexp(80, rate = exp(0.5 * X[, 1]))
#' delta <- rep(c(0L, 1L), 40)
#' fit <- fit_risdr_dual(
#'   X, time, delta = delta, response_type = "survival",
#'   sdr_method = "sir", cov_method = "oas", nslices = 4,
#'   dual_rank = 4, verbose = FALSE, d_max = 2, lambda_grid = c(0, 0.05)
#' )
#' fit$d
#' predict(fit, X[1:2, , drop = FALSE], type = "risk")
#' @name fit_risdr_dual
fit_risdr_dual <- function(X, y, delta = NULL, response_type = c("continuous", "categorical",
    "survival"), dual_rank = 100L, variance_explained = NULL, d = NULL, d_max = 10L, nslices = 4L,
    sdr_method = c("dr", "sir", "save", "phd"), cov_method = c("mec", "oas", "lw", "sample",
        "ridge"), selector = c("cicomp", "icomp", "aic", "caic", "bic"), lambda_grid = seq(0,
        0.3, length.out = 10L), adapt_weights = TRUE, weight_mode = c("c1f", "inverse_c1f",
        "uniform"), support_penalty = FALSE, standardize_dual = TRUE, gene_select_top = NULL,
    gene_select_quantile = 0.99, center = TRUE, scale_X = TRUE, verbose = TRUE, ...) {
    response_type <- match.arg(response_type)
    sdr_method <- match.arg(sdr_method)
    cov_method <- match.arg(cov_method)
    selector <- match.arg(selector)
    weight_mode <- match.arg(weight_mode)
    X <- as.matrix(X)
    if (!is.numeric(X)) {
        stop("`X` must be numeric.", call. = FALSE)
    }
    if (length(y) != nrow(X)) {
        stop("Length of `y` must equal nrow(`X`).", call. = FALSE)
    }
    gene_names <- colnames(X)
    if (is.null(gene_names) || anyNA(gene_names) || any(!nzchar(gene_names)) || anyDuplicated(gene_names)) {
        stop("Dual RISDR requires non-missing, non-empty, unique predictor names.", call. = FALSE)
    }
    if (response_type == "survival" && is.null(delta)) {
        stop("`delta` must be supplied for survival response.", call. = FALSE)
    }
    if (!is.null(gene_select_top)) {
        gene_select_top <- as.integer(gene_select_top)
        if (length(gene_select_top) != 1L || is.na(gene_select_top) || gene_select_top <
            1L) {
            stop("`gene_select_top` must be a positive integer.", call. = FALSE)
        }
    }
    if (!is.numeric(gene_select_quantile) || length(gene_select_quantile) != 1L || is.na(gene_select_quantile) ||
        gene_select_quantile < 0 || gene_select_quantile > 1) {
        stop("`gene_select_quantile` must lie in [0, 1].", call. = FALSE)
    }
    if (verbose) {
        message("[fit_risdr_dual] Step 1/6: removing incomplete outcome records...")
    }
    keep <- stats::complete.cases(y)
    if (!is.null(delta)) {
        keep <- keep & stats::complete.cases(delta)
    }
    X <- X[keep, , drop = FALSE]
    y <- y[keep]
    if (!is.null(delta)) {
        delta <- delta[keep]
    }
    if (nrow(X) < 3L) {
        stop("Too few complete outcome records remain.", call. = FALSE)
    }
    if (verbose) {
        message("[fit_risdr_dual] Data dimensions after cleaning: n = ", nrow(X), ", p = ",
            ncol(X))
    }
    if (verbose) {
        message("[fit_risdr_dual] Step 2/6: constructing dual PCA scores...")
    }
    dual <- dual_pca_scores(X = X, dual_rank = dual_rank, variance_explained = variance_explained,
        center = center, scale_X = scale_X)
    if (verbose) {
        message("[fit_risdr_dual] Retained dual rank: ", dual$dual_rank)
    }
    if (verbose) {
        message("[fit_risdr_dual] Step 3/6: fitting RISDR in dual score space...")
    }
    fit_dual <- fit_risdr_sparse(X = dual$scores, y = y, delta = delta, response_type = response_type,
        d = d, d_max = d_max, nslices = nslices, sdr_method = sdr_method, cov_method = cov_method,
        selector = selector, lambda_grid = lambda_grid, adapt_weights = adapt_weights, weight_mode = weight_mode,
        support_penalty = support_penalty, standardize = standardize_dual, ...)
    selected_d <- as.integer(fit_dual$d)
    if (length(selected_d) != 1L || is.na(selected_d) || selected_d < 1L || selected_d >
        ncol(fit_dual$directions)) {
        stop("Invalid selected structural dimension returned by fit_risdr(): ", fit_dual$d,
            call. = FALSE)
    }
    if (verbose) {
        message("[fit_risdr_dual] Step 4/6: mapping dual directions back to gene space...")
    }
    B_selected_work <- as.matrix(fit_dual$directions)
    B_dense_work <- as.matrix(fit_dual$dense_directions)
    inner_scale <- if (isTRUE(fit_dual$standardize)) {
        as.numeric(fit_dual$scale)
    }
    else {
        rep(1, nrow(B_selected_work))
    }
    if (length(inner_scale) != nrow(B_selected_work) || any(!is.finite(inner_scale)) || any(inner_scale <=
        0)) {
        stop("Inner RISDR standardisation scale does not align with dual directions.", call. = FALSE)
    }
    B_selected_dual_input <- sweep(B_selected_work, 1L, inner_scale, "/")
    B_dense_dual_input <- sweep(B_dense_work, 1L, inner_scale, "/")
    gene_directions <- dual$loadings %*% B_dense_dual_input
    selected_gene_directions <- dual$loadings %*% B_selected_dual_input
    rownames(gene_directions) <- gene_names
    rownames(selected_gene_directions) <- gene_names
    colnames(gene_directions) <- paste0("RISDR_DenseDim", seq_len(ncol(gene_directions)))
    colnames(selected_gene_directions) <- paste0("RISDR_Dim", seq_len(selected_d))
    if (verbose) {
        message("[fit_risdr_dual] Step 5/6: ranking genes by selected sparse-direction norm...")
    }
    loading_norm <- sqrt(rowSums(selected_gene_directions^2))
    if (!is.null(gene_select_top)) {
        selected_idx <- order(loading_norm, decreasing = TRUE)[seq_len(min(gene_select_top,
            length(loading_norm)))]
    }
    else {
        cutoff <- stats::quantile(loading_norm, probs = gene_select_quantile, na.rm = TRUE)
        selected_idx <- which(loading_norm >= cutoff)
    }
    selected_variables <- data.frame(index = selected_idx, variable = gene_names[selected_idx],
        loading_norm = loading_norm[selected_idx], stringsAsFactors = FALSE)
    selected_variables <- selected_variables[order(selected_variables$loading_norm, decreasing = TRUE),
        , drop = FALSE]
    reduced_predictors <- as.matrix(fit_dual$reduced_predictors)
    if (nrow(reduced_predictors) != nrow(X) || ncol(reduced_predictors) != selected_d) {
        stop("Dual core reduced predictors have unexpected dimensions.", call. = FALSE)
    }
    if (verbose) {
        message("[fit_risdr_dual] Step 6/6: dual RISDR fit completed.")
    }
    out <- list(call = match.call(), fit_dual = fit_dual, dual = dual, response_type = response_type,
        requested_d = d, d = selected_d, d_max = fit_dual$d_max, best_lambda = fit_dual$best_lambda,
        dual_rank = dual$dual_rank, dense_dual_directions_input_scale = B_dense_dual_input,
        selected_dual_directions_input_scale = B_selected_dual_input, gene_directions = gene_directions,
        selected_gene_directions = selected_gene_directions, gene_direction_scale = if (isTRUE(scale_X)) {
            "dual-PCA standardised predictor coordinates"
        } else {
            "dual-PCA centred predictor coordinates"
        }, selected_variables = selected_variables, reduced_predictors = reduced_predictors,
        y = y, delta = delta, kept_rows = keep, gene_select_top = gene_select_top, gene_select_quantile = gene_select_quantile,
        standardize_dual = standardize_dual, center = center, scale_X = scale_X)
    class(out) <- "risdr_dual"
    out
}

#' Fit RISDR to real high-dimensional data
#'
#' @param X Predictor matrix.
#' @param y Response vector.
#' @param delta Optional survival censoring indicator.
#' @param response_type Response type.
#' @param variance_quantile Variance filtering threshold.
#' @param ... Additional arguments passed to fit_risdr_sparse().
#'
#' @return Fitted RISDR workflow object.
#' Fit RISDR to a real-data predictor matrix
#'
#' Applies outcome cleaning, low-variance screening, the unified RISDR core,
#' and descriptive loading-based variable ranking. The wrapper returns the
#' reduced predictors computed by the core itself so that centring and
#' standardisation are not silently bypassed.
#'
#'   `"multiclass"`, `"categorical"`, or `"survival"`.
#'   low-variance screen.
#' @return An object of class `risdr_realdata`.
#' @export
#' @details This entry point uses the frozen sparse thesis engine. The
#' existing [fit_risdr()] and [fit_risdr_realdata()] interfaces retain their
#' continuous-response behaviour from version 0.3.1. Survival fits use Efron
#' Cox partial likelihood. Apparent fit statistics and loading ranks are
#' exploratory and do not establish external predictive validity.
#' @name fit_risdr_sparse_realdata
fit_risdr_sparse_realdata <- function(X, y, delta = NULL, response_type = c("continuous",
    "binary", "multiclass", "categorical", "survival"), variance_quantile = 0.25, ...) {
    response_type <- match.arg(response_type)
    X <- as.matrix(X)
    if (!is.numeric(X)) {
        stop("`X` must be numeric.", call. = FALSE)
    }
    if (length(y) != nrow(X)) {
        stop("Length of `y` must equal nrow(`X`).", call. = FALSE)
    }
    if (is.null(colnames(X))) {
        colnames(X) <- paste0("X", seq_len(ncol(X)))
    }
    if (anyNA(colnames(X)) || any(!nzchar(colnames(X))) || anyDuplicated(colnames(X))) {
        stop("Predictor names must be non-missing, non-empty, and unique.", call. = FALSE)
    }
    if (!is.numeric(variance_quantile) || length(variance_quantile) != 1L || is.na(variance_quantile) ||
        variance_quantile < 0 || variance_quantile >= 1) {
        stop("`variance_quantile` must be a scalar in [0, 1).", call. = FALSE)
    }
    if (response_type == "survival") {
        surv_obj <- .thesis_prepare_survival_response(time = y, delta = delta)
        keep_rows <- surv_obj$keep
        X_clean <- X[keep_rows, , drop = FALSE]
        y_clean <- surv_obj$time
        delta_clean <- surv_obj$delta
        core_response_type <- "survival"
    }
    else {
        keep_rows <- stats::complete.cases(y)
        X_clean <- X[keep_rows, , drop = FALSE]
        y_clean <- y[keep_rows]
        delta_clean <- NULL
        core_response_type <- if (response_type %in% c("binary", "multiclass", "categorical")) {
            "categorical"
        }
        else {
            "continuous"
        }
    }
    if (nrow(X_clean) < 3L) {
        stop("Too few complete outcome records remain.", call. = FALSE)
    }
    X_filtered <- .thesis_filter_low_variance(X = X_clean, variance_quantile = variance_quantile)
    kept_vars <- attr(X_filtered, "kept_variables")
    if (is.null(kept_vars)) {
        kept_vars <- colnames(X_filtered)
    }
    kept_vars <- as.character(kept_vars)
    if (length(kept_vars) != ncol(X_filtered) || !identical(kept_vars, colnames(X_filtered))) {
        stop("Low-variance screening did not preserve an auditable variable-name mapping.",
            call. = FALSE)
    }
    fit <- fit_risdr_sparse(X = X_filtered, y = y_clean, delta = delta_clean, response_type = core_response_type,
        ...)
    B <- as.matrix(fit$directions)
    if (nrow(B) != ncol(X_filtered) || ncol(B) != fit$d) {
        stop("Core direction matrix does not align with the filtered predictors.", call. = FALSE)
    }
    rownames(B) <- colnames(X_filtered)
    loading_norm <- sqrt(rowSums(B^2))
    active <- which(loading_norm > 1e-08)
    selected_variables <- data.frame(index = active, variable = colnames(X_filtered)[active],
        loading_norm = loading_norm[active], stringsAsFactors = FALSE)
    selected_variables <- selected_variables[order(selected_variables$loading_norm, decreasing = TRUE),
        , drop = FALSE]
    reduced_predictors <- as.matrix(fit$reduced_predictors)
    if (nrow(reduced_predictors) != nrow(X_filtered) || ncol(reduced_predictors) != fit$d) {
        stop("Core reduced predictors have unexpected dimensions.", call. = FALSE)
    }
    out <- list(call = match.call(), fit = fit, response_type = response_type, core_response_type = core_response_type,
        selected_variables = selected_variables, reduced_predictors = reduced_predictors,
        filtered_predictors = X_filtered, kept_variables = kept_vars, kept_rows = keep_rows,
        y = y_clean, delta = delta_clean, variance_quantile = variance_quantile)
    class(out) <- "risdr_sparse_realdata"
    out
}

#' Fit sparse SDR directions over a lambda grid
#'
#' Accepts either an explicit dense direction matrix or a historical kernel
#' object containing `directions` or `vectors`.
#'
#' @param kernel_obj Optional historical kernel object.
#' @param directions Optional dense direction matrix.
#' @param d Structural dimension.
#' @param lambda_grid Numeric vector of tuning values.
#' @param penalty_weights Optional user-supplied penalty weights.
#' @param adapt_weights Logical; derive weights from `Sigma` when TRUE.
#' @param Sigma Optional covariance matrix.
#' @param weight_mode Adaptive weighting mode.
#' @param tol Numerical tolerance.
#' @return Sparse-grid object.
#' @export
#' @name fit_sparse_grid
fit_sparse_grid <- function(kernel_obj = NULL, directions = NULL, d = 2L, lambda_grid = seq(0,
    0.5, length.out = 25L), penalty_weights = NULL, adapt_weights = FALSE, Sigma = NULL,
    weight_mode = c("c1f", "inverse_c1f", "uniform"), tol = 1e-10) {
    weight_mode <- match.arg(weight_mode)
    lambda_grid <- as.numeric(lambda_grid)
    if (length(lambda_grid) < 1L || anyNA(lambda_grid) || any(!is.finite(lambda_grid)) ||
        any(lambda_grid < 0)) {
        stop("`lambda_grid` must contain finite non-negative values.", call. = FALSE)
    }
    if (is.null(directions)) {
        if (is.null(kernel_obj)) {
            stop("Supply `directions` or `kernel_obj`.", call. = FALSE)
        }
        if (!is.null(kernel_obj$directions)) {
            directions <- kernel_obj$directions
        }
        else if (!is.null(kernel_obj$vectors)) {
            directions <- kernel_obj$vectors
        }
        else {
            stop("`kernel_obj` contains no recognised direction matrix.", call. = FALSE)
        }
    }
    directions <- as.matrix(directions)
    d <- as.integer(d)
    if (length(d) != 1L || is.na(d) || d < 1L || d > ncol(directions)) {
        stop("Invalid structural dimension `d`.", call. = FALSE)
    }
    V_dense <- directions[, seq_len(d), drop = FALSE]
    p <- nrow(V_dense)
    if (is.null(penalty_weights)) {
        if (adapt_weights) {
            if (is.null(Sigma)) {
                warning("`adapt_weights = TRUE` but `Sigma` is NULL; using uniform weights.",
                  call. = FALSE)
                penalty_weights <- rep(1, p)
            }
            else {
                penalty_weights <- compute_penalty_weights(Sigma = Sigma, mode = weight_mode,
                  tol = tol)
            }
        }
        else {
            penalty_weights <- rep(1, p)
        }
    }
    else {
        penalty_weights <- .thesis_expand_penalty_weights(penalty_weights, p = p, tol = tol)
    }
    fits <- vector("list", length(lambda_grid))
    names(fits) <- paste0("lambda_", format(lambda_grid, trim = TRUE))
    for (i in seq_along(lambda_grid)) {
        fits[[i]] <- weighted_sparsify_directions(V = V_dense, lambda = lambda_grid[i], weights = penalty_weights,
            tol = tol)
    }
    list(fits = fits, lambda_grid = lambda_grid, penalty_weights = penalty_weights, dense_directions = V_dense,
        weight_mode = weight_mode, adapt_weights = adapt_weights)
}

.thesis_make_slices <- function(y, nslices = 6, type = c("quantile", "equal_width")) {
    if (missing(y) || is.null(y)) {
        stop("`y` must be supplied.", call. = FALSE)
    }
    if (!is.numeric(y)) {
        stop("`y` must be numeric for Phase 1.", call. = FALSE)
    }
    y <- as.numeric(y)
    if (anyNA(y)) {
        stop("`y` contains missing values.", call. = FALSE)
    }
    if (any(!is.finite(y))) {
        stop("`y` contains non-finite values.", call. = FALSE)
    }
    nslices <- .thesis_check_nslices(nslices, length(y))
    type <- match.arg(type)
    if (length(unique(y)) < nslices) {
        stop("`y` has fewer unique values than `nslices`.", call. = FALSE)
    }
    if (type == "quantile") {
        probs <- seq(0, 1, length.out = nslices + 1)
        breaks <- stats::quantile(y, probs = probs, na.rm = TRUE, type = 7)
        breaks <- unique(as.numeric(breaks))
        if (length(breaks) < 3) {
            stop("Quantile slicing failed because too few unique breakpoints were produced.",
                call. = FALSE)
        }
        slices <- cut(y, breaks = breaks, include.lowest = TRUE, labels = FALSE)
    }
    if (type == "equal_width") {
        breaks <- seq(min(y), max(y), length.out = nslices + 1)
        slices <- cut(y, breaks = breaks, include.lowest = TRUE, labels = FALSE)
    }
    if (anyNA(slices)) {
        stop("Slicing produced missing slice labels. Check `y` and slicing parameters.",
            call. = FALSE)
    }
    as.integer(slices)
}

.thesis_matrix_inv_sqrt <- function(Sigma, eps = 1e-08) {
    Sigma <- .thesis_check_cov_matrix(Sigma)
    eig <- eigen(Sigma, symmetric = TRUE)
    values <- pmax(eig$values, eps)
    inv_sqrt <- eig$vectors %*% diag(1/sqrt(values), nrow = length(values)) %*% t(eig$vectors)
    (inv_sqrt + t(inv_sqrt))/2
}

.thesis_prepare_survival_response <- function(time, delta) {
    keep <- stats::complete.cases(time, delta)
    out <- list(time = as.numeric(time[keep]), delta = as.numeric(delta[keep]), keep = keep)
    return(out)
}

#' Print risdr object
#'
#' @param x Object of class "risdr".
#' @param ... Additional arguments passed to internal methods.
#'
#' @return Invisibly returns x.
#' @export
#' @name print.risdr_sparse
print.risdr_sparse <- function(x, ...) {
    cat("Regularised and Information-Theoretic SDR fit\n")
    cat("--------------------------------------------------\n")
    cat("SDR method       :", toupper(x$sdr_method), "\n")
    cat("Covariance       :", toupper(x$cov_method), "\n")
    cat("Stabilised       :", x$stabilize, "\n")
    cat("Stabilisation    :", x$stabilization, "\n")
    cat("Selected d       :", x$d, "\n")
    cat("Selector         :", toupper(x$selector), "\n")
    cat("Number of slices :", x$nslices, "\n")
    cat("Observations     :", nrow(x$X), "\n")
    cat("Predictors       :", ncol(x$X), "\n")
    invisible(x)
}

#' Print method for dual RISDR objects
#'
#' @param x Object of class `risdr_dual`.
#' @param ... Additional arguments passed to internal methods.
#'
#' @export
#' @name print.risdr_dual
print.risdr_dual <- function(x, ...) {
    cat("\nDual high-dimensional RISDR fit\n")
    cat("--------------------------------\n")
    cat("Response type       :", x$response_type, "\n")
    cat("Dual rank retained  :", x$dual_rank, "\n")
    cat("Structural dimension:", x$d, "\n")
    cat("Selected variables  :", nrow(x$selected_variables), "\n")
    cat("Selected dimension  :", x$fit_dual$d, "\n")
    cat("Selection criterion :", x$fit_dual$selector, "\n")
    invisible(x)
}

#' Print real-data RISDR workflow
#'
#' @param x Object of class risdr_realdata.
#' @param ... Additional arguments.
#' @export
#' @name print.risdr_sparse_realdata
print.risdr_sparse_realdata <- function(x, ...) {
    cat("\n")
    cat("RISDR Real-Data Workflow\n")
    cat("-------------------------\n")
    cat("Number of selected variables:", nrow(x$selected_variables), "\n")
    cat("Reduced dimension:", ncol(x$reduced_predictors), "\n")
    invisible(x)
}

#' Print summary of risdr object
#'
#' @param x Object of class "summary.risdr_sparse".
#' @param ... Additional arguments passed to internal methods.
#'
#' @return Invisibly returns x.
#' @export
#' @name print.summary.risdr_sparse
print.summary.risdr_sparse <- function(x, ...) {
    cat("Summary of risdr fit\n")
    cat("--------------------------------------------------\n")
    cat("Method              :", toupper(x$method), "\n")
    cat("Covariance          :", toupper(x$covariance), "\n")
    cat("Selected dimension  :", x$selected_dimension, "\n")
    cat("Selector            :", toupper(x$selector), "\n\n")
    cat("Leading eigenvalues:\n")
    print(x$eigenvalues)
    cat("\nDimension selection table:\n")
    print(x$dimension_table)
    cat("\nCovariance diagnostics:\n")
    print(x$covariance_diagnostics[1:4])
    invisible(x)
}

#' Slice response for inverse regression
#'
#' Constructs slice labels for continuous, categorical, or censored survival
#' responses. For censored survival data, double slicing is used by first
#' splitting on censoring status and then slicing observed time within each
#' status group.
#'
#' @param y Response vector. For survival data, observed time.
#' @param nslices Number of slices for continuous data or per censoring-status
#'   group for survival data.
#' @param response_type One of `"continuous"`, `"categorical"`, or
#'   `"survival"`.
#' @param delta Optional 0/1 event indicator for survival data.
#' @return A list containing integer slice labels and metadata.
#' @export
#' @name slice_response
NULL
slice_response <- function(y, nslices = 5L, response_type = c("continuous", "categorical",
    "survival"), delta = NULL) {
    response_type <- match.arg(response_type)
    if (length(nslices) != 1L || is.na(nslices) || nslices < 1L) {
        stop("`nslices` must be a positive integer.", call. = FALSE)
    }
    nslices <- as.integer(nslices)
    if (response_type == "continuous") {
        if (!is.numeric(y)) {
            stop("For continuous response, `y` must be numeric.", call. = FALSE)
        }
        if (anyNA(y)) {
            stop("`y` contains missing values.", call. = FALSE)
        }
        probs <- seq(0, 1, length.out = nslices + 1L)
        brks <- unique(stats::quantile(y, probs = probs, na.rm = TRUE, type = 7))
        if (length(brks) <= 2L) {
            groups <- rep(1L, length(y))
        }
        else {
            groups <- cut(y, breaks = brks, include.lowest = TRUE, labels = FALSE)
        }
        groups <- as.integer(groups)
        return(list(groups = groups, nslices = length(unique(groups)), labels = sort(unique(groups)),
            response_type = "continuous", requested_nslices = nslices))
    }
    if (response_type == "categorical") {
        if (anyNA(y)) {
            stop("`y` contains missing values.", call. = FALSE)
        }
        groups <- as.integer(as.factor(y))
        return(list(groups = groups, nslices = length(unique(groups)), labels = sort(unique(groups)),
            response_type = "categorical", requested_nslices = nslices))
    }
    if (!is.numeric(y)) {
        stop("For survival response, observed time `y` must be numeric.", call. = FALSE)
    }
    if (is.null(delta)) {
        stop("For survival response, `delta` must be supplied.", call. = FALSE)
    }
    if (length(delta) != length(y)) {
        stop("`delta` must have the same length as `y`.", call. = FALSE)
    }
    if (anyNA(y) || anyNA(delta)) {
        stop("Survival time and `delta` must be complete before slicing.", call. = FALSE)
    }
    if (any(!is.finite(y)) || any(y <= 0)) {
        stop("Survival times must be finite and strictly positive.", call. = FALSE)
    }
    delta <- as.integer(delta)
    if (!all(delta %in% c(0L, 1L))) {
        stop("`delta` must contain only 0/1 values.", call. = FALSE)
    }
    groups <- integer(length(y))
    current_label <- 1L
    for (status in c(0L, 1L)) {
        idx <- which(delta == status)
        if (length(idx) == 0L) {
            next
        }
        y_sub <- y[idx]
        probs <- seq(0, 1, length.out = nslices + 1L)
        brks <- unique(stats::quantile(y_sub, probs = probs, na.rm = TRUE, type = 7))
        if (length(brks) <= 2L) {
            groups[idx] <- current_label
            current_label <- current_label + 1L
        }
        else {
            raw_groups <- cut(y_sub, breaks = brks, include.lowest = TRUE, labels = FALSE)
            uniq <- sort(unique(raw_groups))
            relabel <- match(raw_groups, uniq) + current_label - 1L
            groups[idx] <- relabel
            current_label <- max(relabel) + 1L
        }
    }
    list(groups = groups, nslices = length(unique(groups)), labels = sort(unique(groups)),
        response_type = "survival", requested_nslices = nslices, status_counts = table(delta))
}

.thesis_stabilize_cov <- function(Sigma, method = c("eigenfloor", "ridge", "nearest_pd"),
    eps = 1e-06, lambda = 1e-04, keep_diag = TRUE) {
    method <- match.arg(method)
    if (method == "eigenfloor") {
        return(.thesis_stabilize_eigenfloor(Sigma, eps = eps))
    }
    if (method == "ridge") {
        return(.thesis_stabilize_ridge(Sigma, lambda = lambda))
    }
    if (method == "nearest_pd") {
        return(.thesis_stabilize_nearest_pd(Sigma, keep_diag = keep_diag))
    }
}

.thesis_stabilize_eigenfloor <- function(Sigma, eps = 1e-06) {
    Sigma <- .thesis_check_cov_matrix(Sigma)
    if (!is.numeric(eps) || length(eps) != 1 || eps <= 0) {
        stop("`eps` must be a single positive numeric value.", call. = FALSE)
    }
    eig <- eigen(Sigma, symmetric = TRUE)
    values <- pmax(eig$values, eps)
    Sigma_stable <- eig$vectors %*% diag(values, nrow = length(values)) %*% t(eig$vectors)
    Sigma_stable <- (Sigma_stable + t(Sigma_stable))/2
    Sigma_stable
}

.thesis_stabilize_nearest_pd <- function(Sigma, keep_diag = TRUE) {
    Sigma <- .thesis_check_cov_matrix(Sigma)
    if (!requireNamespace("Matrix", quietly = TRUE)) {
        stop("Package `Matrix` is required for nearest positive definite stabilisation.",
            call. = FALSE)
    }
    Sigma_pd <- Matrix::nearPD(Sigma, corr = FALSE, keepDiag = keep_diag)$mat
    Sigma_pd <- as.matrix(Sigma_pd)
    Sigma_pd <- (Sigma_pd + t(Sigma_pd))/2
    Sigma_pd
}

.thesis_stabilize_ridge <- function(Sigma, lambda = 1e-04) {
    Sigma <- .thesis_check_cov_matrix(Sigma)
    if (!is.numeric(lambda) || length(lambda) != 1 || lambda < 0) {
        stop("`lambda` must be a single non-negative numeric value.", call. = FALSE)
    }
    p <- ncol(Sigma)
    Sigma_stable <- Sigma + lambda * diag(p)
    Sigma_stable <- (Sigma_stable + t(Sigma_stable))/2
    Sigma_stable
}

.thesis_standardize_by_cov <- function(X, Sigma, center = NULL, eps = 1e-08) {
    X <- .thesis_check_X(X)
    Sigma <- .thesis_check_cov_matrix(Sigma)
    if (ncol(X) != ncol(Sigma)) {
        stop("Number of columns in `X` must match dimension of `Sigma`.", call. = FALSE)
    }
    if (is.null(center)) {
        center <- colMeans(X)
    }
    Xc <- sweep(X, 2, center, "-")
    Sigma_inv_sqrt <- .thesis_matrix_inv_sqrt(Sigma, eps = eps)
    Z <- Xc %*% Sigma_inv_sqrt
    list(Z = Z, center = center, Sigma_inv_sqrt = Sigma_inv_sqrt)
}

#' Summarise sparsity pattern
#'
#' @param V Direction matrix.
#' @param tol Threshold for active support.
#' @return Sparsity summary.
#' @export
#' @name summarise_sparsity
summarise_sparsity <- function(V, tol = 1e-08) {
    V <- as.matrix(V)
    active_rows <- which(rowSums(abs(V)) > tol)
    active_by_direction <- lapply(seq_len(ncol(V)), function(j) {
        which(abs(V[, j]) > tol)
    })
    list(n_active = length(active_rows), active_rows = active_rows, active_by_direction = active_by_direction)
}

#' Summarise risdr object
#'
#' @param object Object of class "risdr".
#'
#' @return A list summary.
#' @param ... Additional arguments passed to internal methods.
#' @export
#' @name summary.risdr_sparse
summary.risdr_sparse <- function(object, ...) {
    out <- list(method = object$sdr_method, covariance = object$cov_method, selected_dimension = object$d,
        selector = object$selector, eigenvalues = head(object$eigenvalues, 10), dimension_table = object$d_table,
        covariance_diagnostics = .thesis_cov_diagnostics(object$Sigma))
    class(out) <- "summary.risdr_sparse"
    out
}

#' Summary method for dual RISDR objects
#'
#' @param object Object of class `risdr_dual`.
#' @param top_n Number of selected variables to print.
#' @param ... Additional arguments passed to internal methods.
#'
#' @export
#' @name summary.risdr_dual
summary.risdr_dual <- function(object, top_n = 20L, ...) {
    print(object)
    cat("\nTop selected variables\n")
    print(utils::head(object$selected_variables, top_n))
    cat("\nDual-space model summary\n")
    print(summary(object$fit_dual))
    invisible(object)
}

#' Weighted soft-threshold operator
#'
#' @param z Numeric vector.
#' @param lambda Non-negative tuning parameter.
#' @param weights Penalty weights.
#' @param tol Numerical tolerance.
#' @return Thresholded vector.
#' @export
#' @name weighted_soft_threshold
weighted_soft_threshold <- function(z, lambda, weights = NULL, tol = 1e-10) {
    z <- as.numeric(z)
    if (length(lambda) != 1L || is.na(lambda) || !is.finite(lambda) || lambda < 0) {
        stop("`lambda` must be a finite non-negative scalar.", call. = FALSE)
    }
    if (is.null(weights)) {
        weights <- rep(1, length(z))
    }
    weights <- .thesis_expand_penalty_weights(weights, p = length(z), tol = tol)
    sign(z) * pmax(abs(z) - lambda * weights, 0)
}

#' Weighted sparse directions from dense SDR directions
#'
#' @param V Dense direction matrix.
#' @param lambda Non-negative tuning parameter.
#' @param weights Variable-level penalty weights.
#' @param tol Numerical tolerance.
#' @return Sparse direction matrix.
#' @export
#' @name weighted_sparsify_directions
weighted_sparsify_directions <- function(V, lambda, weights = NULL, tol = 1e-10) {
    V <- as.matrix(V)
    if (!is.numeric(V)) {
        stop("`V` must be numeric.", call. = FALSE)
    }
    p <- nrow(V)
    d <- ncol(V)
    if (is.null(weights)) {
        weights <- rep(1, p)
    }
    weights <- .thesis_expand_penalty_weights(weights, p = p, tol = tol)
    out <- matrix(0, nrow = p, ncol = d)
    for (j in seq_len(d)) {
        vj <- V[, j]
        vj_thr <- weighted_soft_threshold(vj, lambda = lambda, weights = weights, tol = tol)
        if (sum(abs(vj_thr)) < tol) {
            vj_thr <- vj
        }
        out[, j] <- .thesis_.risdr_safe_normalise(vj_thr, tol = tol)
    }
    rownames(out) <- rownames(V)
    colnames(out) <- colnames(V)
    out
}
